url: "https://github.com/Ismaelrd21"
baseurl: ""

# Site settings
title: "Ismael Isaías Rivera Delgado"
email: "ismael.riveradelgado.ing@gmail.com"
description: "Portafolio profesional enfocado en automatización, robótica, inteligencia artificial e investigación aplicada."

social:
  - title: linkedin
    url: "https://www.linkedin.com/in/ismaelriveradelgado/"
  - title: github
    url: "https://github.com/Ismaelrd21"

markdown: kramdown
permalink: pretty
